# Generated by Django 5.1.6 on 2025-06-03 11:07

import bookstore.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fotoPerfil',
            field=models.ImageField(default=9, upload_to=bookstore.models.RenameImage('ftPerfil/')),
            preserve_default=False,
        ),
    ]
