# Generated by Django 5.1.6 on 2025-06-09 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_usuario_fotoperfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.livro'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.usuario'),
        ),
    ]
